#!/usr/bin/env bash

function main {
  local script_dir
  script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
  local repo_dir="${script_dir}/.."

  cd "${repo_dir}" || return 1
  echo "Running clang-format ..."
  find papinst \( -iname '*.h' -o -iname '*.cpp' \) -exec echo {} \; \
    -exec clang-format -i {} \;
  find examples \( -iname '*.h' -o -iname '*.cpp' \) \
    -not -path "*/build/*" -exec echo {} \; \
    -exec clang-format -i {} \;

  echo -e "\nRunning black ..."
  black .

  echo -e "\nFormatted paptools code."
}

main "$@"
