#!/usr/bin/env bash
# Wrapper to allow running pathinst using CMAKE_<LANG>_COMPILER_LAUNCHER.

function main
{
  local script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
  local wrapper_args="--verbose --dry-run"
  if [ -n "${PATHINST_WRAPPER_ARGS}" ]; then
    wrapper_args="${PATHINST_WRAPPER_ARGS}"
  fi
  "${script_dir}/pathinst" ${wrapper_args} -- "$@"
}

main "$@"
