#!/usr/bin/env bash

function main {
  local script_dir
  script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
  local repo_dir="${script_dir}/.."

  cd "${repo_dir}" || return 1
  cmake -E chdir build ./demo_unit_tests
}

main "$@"
